name: Test Secret
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret availability
        env:
          MY_SECRET: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "::error::Secret is not set or is empty."
            exit 1
          else
            echo "Secret is set and available. Value is redacted."
            exit 0
          fi