name: Test Secret
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret availability
        env:
          SNOWFLAKE_ACCOUNT_DEV_SECRET: ${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}
          SNOWFLAKE_USER_DEV_SECRET: ${{ secrets.SNOWFLAKE_USER_DEV }}
          SNOWFLAKE_PASSWORD_DEV_SECRET: ${{ secrets.SNOWFLAKE_PASSWORD_DEV }}
          SNOWFLAKE_ROLE_DEV_SECRET: ${{ secrets.SNOWFLAKE_ROLE_DEV }}
          SNOWFLAKE_DATABASE_DEV_SECRET: ${{ secrets.SNOWFLAKE_DATABASE_DEV }}
          SNOWFLAKE_SCHEMA_DEV_SECRET: ${{ secrets.SNOWFLAKE_SCHEMA_DEV }}
          SNOWFLAKE_WAREHOUSE_DEV_SECRET: ${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}
        run: |
          if [ -z "$SNOWFLAKE_ACCOUNT_DEV_SECRET" ]; then
            echo "::error::SNOWFLAKE_ACCOUNT_DEV Secret is not set or is empty."
          else
            echo "SNOWFLAKE_ACCOUNT_DEV Secret is set and available. Value is redacted."
            exit 0
          fi
          if [ -z "$SNOWFLAKE_USER_DEV_SECRET" ]; then
            echo "::error::SNOWFLAKE_USER_DEV Secret is not set or is empty."
          else
            echo "SNOWFLAKE_USER_DEV Secret is set and available. Value is redacted."
          fi
          if [ -z "$SNOWFLAKE_PASSWORD_DEV_SECRET" ]; then
            echo "::error::SNOWFLAKE_PASSWORD_DEV Secret is not set or is empty."
          else
            echo "SNOWFLAKE_PASSWORD_DEV Secret is set and available. Value is redacted."
          fi
          if [ -z "$SNOWFLAKE_ROLE_DEV_SECRET" ]; then
            echo "::error::SNOWFLAKE_ROLE_DEV Secret is not set or is empty."
          else
            echo "SNOWFLAKE_ROLE_DEV Secret is set and available. Value is redacted."
          fi
          if [ -z "$SNOWFLAKE_DATABASE_DEV_SECRET" ]; then
            echo "::error::SNOWFLAKE_DATABASE_DEV Secret is not set or is empty."
          else
            echo "SNOWFLAKE_DATABASE_DEV Secret is set and available. Value is redacted."
          fi
          if [ -z "$SNOWFLAKE_SCHEMA_DEV_SECRET" ]; then
            echo "::error::SNOWFLAKE_SCHEMA_DEV Secret is not set or is empty."
          else
            echo "SNOWFLAKE_SCHEMA_DEV Secret is set and available. Value is redacted."
          fi
          if [ -z "$SNOWFLAKE_WAREHOUSE_DEV_SECRET" ]; then
            echo "::error::SNOWFLAKE_WAREHOUSE_DEV Secret is not set or is empty."
          else
            echo "SNOWFLAKE_WAREHOUSE_DEV Secret is set and available. Value is redacted."
          fi
          echo "============ end of test ================
